### ISSUE TITLE
K8S Bug 55278 marked stale

### ISSUE THREAD

**Issue by RisingPhorce** [aws-samples/aws-workshop-for-kubernetes#403] opened 2018-03-19 17:51 UTC
The QoS bug referenced in https://github.com/aws-samples/aws-workshop-for-kubernetes/tree/master/01-path-basics/103-kubernetes-concepts#quality-of-service was recently marked stale by the k8s-ci-bot.  

https://github.com/kubernetes/kubernetes/issues/55278

**Comment by christopherhein** [comment] 2018-05-15 21:16
Apparently this is a feature of kops, not a bug. Closing this issue.

**Closed by christopherhein** 2018-05-15 21:16 UTC
