### ISSUE TITLE
Fluentd daemon fails to start

### ISSUE THREAD

**Issue by jicowan** [aws-samples/aws-workshop-for-kubernetes#287] opened 2017-12-04 21:20 UTC
After editing the configuration files, the logging daemon fails to start.  Below is an excerpt from kubectl: 
```
kubectl get pods -w -n logging
NAME            READY     STATUS             RESTARTS   AGE
fluentd-1pljd   0/1       CrashLoopBackOff   1          10s
fluentd-71cps   0/1       CrashLoopBackOff   1          10s
fluentd-h79sh   0/1       CrashLoopBackOff   1          10s
fluentd-hn1bf   0/1       CrashLoopBackOff   1          10s
fluentd-lrf23   0/1       CrashLoopBackOff   1          10s
fluentd-nbwwg   0/1       CrashLoopBackOff   1          10s
fluentd-71cps   1/1       Running   2         20s
fluentd-1pljd   0/1       CrashLoopBackOff   1         20s
fluentd-h79sh   0/1       CrashLoopBackOff   1         20s
fluentd-71cps   0/1       Completed   2         21s
fluentd-1pljd   1/1       Running   2         21s
fluentd-h79sh   1/1       Running   2         22s
fluentd-hn1bf   0/1       CrashLoopBackOff   1         22s
fluentd-1pljd   0/1       Completed   2         22s
fluentd-h79sh   0/1       Completed   2         23s
fluentd-hn1bf   1/1       Running   2         23s
fluentd-nbwwg   0/1       CrashLoopBackOff   1         24s
fluentd-lrf23   0/1       CrashLoopBackOff   1         24s
fluentd-hn1bf   0/1       Completed   2         24s
fluentd-lrf23   1/1       Running   2         25s
fluentd-nbwwg   1/1       Running   2         25s
fluentd-nbwwg   0/1       Completed   2         26s
fluentd-lrf23   0/1       Completed   2         27s
fluentd-lrf23   0/1       CrashLoopBackOff   2         30s
fluentd-nbwwg   0/1       CrashLoopBackOff   2         30s
fluentd-h79sh   0/1       CrashLoopBackOff   2         30s
fluentd-71cps   0/1       CrashLoopBackOff   2         30s
fluentd-hn1bf   0/1       CrashLoopBackOff   2         30s
fluentd-1pljd   0/1       CrashLoopBackOff   2         30s
fluentd-h79sh   1/1       Running   3         44s
fluentd-71cps   1/1       Running   3         45s
fluentd-h79sh   0/1       Completed   3         45s
fluentd-hn1bf   1/1       Running   3         45s
fluentd-71cps   0/1       Completed   3         46s
fluentd-hn1bf   0/1       Completed   3         46s
fluentd-1pljd   1/1       Running   3         46s
fluentd-1pljd   0/1       Completed   3         47s
fluentd-h79sh   0/1       CrashLoopBackOff   3         50s
fluentd-71cps   0/1       CrashLoopBackOff   3         50s
fluentd-hn1bf   0/1       CrashLoopBackOff   3         50s
fluentd-1pljd   0/1       CrashLoopBackOff   3         50s
```

I've assigned an IAM role to the nodes which appears below.  I've removed my account number for security: 

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "logs:DescribeLogGroups"
            ],
            "Resource": [
                "arn:aws:logs:us-east-1:<account>:*:*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "logs:DescribeLogStreams"
            ],
            "Resource": [
                "arn:aws:logs:us-east-1:<account>:log-group:kubernetes-logs:log-stream:*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "logs:CreateLogStream",
                "logs:PutLogEvents"
            ],
            "Resource": [
                "arn:aws:logs:us-east-1:<account>:log-group:kubernetes-logs:log-stream:fluentd-cloudwatch"
            ]
        }
    ]
}
```

I've pulled the latest version of this repository before I ran through the instructions.

**Comment by jicowan** [comment] 2017-12-05 06:38
Additional logs from K8
```
2017-12-05 06:35:15 +0000 [error]: unexpected error error_class=NameError error=#&lt;NameError: uninitialized constant Aws::CloudWatchLogs&gt;
  2017-12-05 06:35:15 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluent-plugin-cloudwatch-logs-0.3.3/lib/fluent/plugin/out_cloudwatch_logs.rb:67:in `start'
  2017-12-05 06:35:15 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.39/lib/fluent/agent.rb:71:in `block in start'
  2017-12-05 06:35:15 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.39/lib/fluent/agent.rb:70:in `each'
  2017-12-05 06:35:15 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.39/lib/fluent/agent.rb:70:in `start'
  2017-12-05 06:35:15 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.39/lib/fluent/root_agent.rb:108:in `start'
  2017-12-05 06:35:15 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.39/lib/fluent/engine.rb:237:in `start'
  2017-12-05 06:35:15 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.39/lib/fluent/engine.rb:187:in `run'
  2017-12-05 06:35:15 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.39/lib/fluent/supervisor.rb:570:in `run_engine'
  2017-12-05 06:35:15 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.39/lib/fluent/supervisor.rb:162:in `block in start'
  2017-12-05 06:35:15 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.39/lib/fluent/supervisor.rb:366:in `main_process'
  2017-12-05 06:35:15 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.39/lib/fluent/supervisor.rb:339:in `block in supervise'
  2017-12-05 06:35:15 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.39/lib/fluent/supervisor.rb:338:in `fork'
  2017-12-05 06:35:15 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.39/lib/fluent/supervisor.rb:338:in `supervise'
  2017-12-05 06:35:15 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.39/lib/fluent/supervisor.rb:156:in `start'
  2017-12-05 06:35:15 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.39/lib/fluent/command/fluentd.rb:173:in `&lt;top (required)&gt;'
  2017-12-05 06:35:15 +0000 [error]: /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2017-12-05 06:35:15 +0000 [error]: /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2017-12-05 06:35:15 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.39/bin/fluentd:5:in `&lt;top (required)&gt;'
  2017-12-05 06:35:15 +0000 [error]: /usr/bin/fluentd:22:in `load'
  2017-12-05 06:35:15 +0000 [error]: /usr/bin/fluentd:22:in `&lt;main&gt;'
2017-12-05 06:35:15 +0000 [info]: shutting down fluentd
2017-12-05 06:35:15 +0000 [info]: shutting down output type="null" plugin_id="object:2b179ad32b24"
2017-12-05 06:35:15 +0000 [info]: shutting down output type="rewrite_tag_filter" plugin_id="object:2b179b264a84"
2017-12-05 06:35:15 +0000 [info]: process finished code=0
2017-12-05 06:35:15 +0000 [warn]: process died within 1 second. exit.
```

**Comment by arun-gupta** [comment] 2017-12-12 04:03
Able to reproduce the issue

**Comment by mefellows** [comment] 2017-12-14 05:54
Could be related to https://github.com/aws/aws-sdk-ruby/issues/1590?

**Comment by Parkalla** [comment] 2017-12-14 06:46
I have the same Problem.
I see the following Errors in "/var/log/amazon/ssm/errors.log"
2017-12-14 06:36:11 ERROR [HandleAwsError @ awserr.go.48] [instanceID=i-06bcc9d97ba5e7efc] [HealthCheck] error when calling AWS APIs. error details - NoCredentialProviders: no valid providers in chain. Deprecated.
        For verbose messaging see aws.Config.CredentialsChainVerboseErrors

**Comment by edsiper** [comment] 2017-12-15 21:57
[sorry for the delay, crazy days after confs]

@arun-gupta  Looks like it's related to the CloudWatch plugin, which Fluentd docker image are you using ?

**Comment by arun-gupta** [comment] 2017-12-15 22:48
@edsiper complete instructions at https://github.com/aws-samples/aws-workshop-for-kubernetes/tree/master/cluster-logging

Specific image is `quay.io/coreos/fluentd-kubernetes:v0.12-cloudwatch` and used at https://github.com/aws-samples/aws-workshop-for-kubernetes/blob/master/cluster-logging/templates/fluentd-ds.yaml

**Comment by ggulati2** [comment] 2017-12-26 12:55
Is there an update on this issue? I get the similar error during my setup 
@arun-gupta

**Comment by MCLDG** [comment] 2018-01-07 04:16
This can be temporarily fixed by replacing the image used in fluentd-ds.yaml as follows:

image: quay.io/coreos/fluentd-kubernetes:v0.12.33-cloudwatch

Still requires a proper fix though as the latest fluentd image does not work.

**Comment by arun-gupta** [comment] 2018-01-08 04:49
@edsiper can you take a closer look?

**Closed** 2018-04-23 21:37 UTC
