### ISSUE TITLE
204-cluster-logging-with-EFK - unable to deploy the fluentd-ds.yml file

### ISSUE THREAD

**Issue by arunkumarmurugesan** [aws-samples/aws-workshop-for-kubernetes#415] opened 2018-04-06 06:59 UTC
I have followed the instruction as per README. And while deploying fluentd-ds.yml file it keep crashing off the pods.

When I checked pod log. I found an error below. 

2018-04-06 06:49:32 +0000 [info]: reading config file path="/fluentd/etc/fluentd.conf"
2018-04-06 06:49:32 +0000 [info]: starting fluentd-0.12.39
2018-04-06 06:49:33 +0000 [info]: gem 'fluent-mixin-config-placeholders' version '0.4.0'
2018-04-06 06:49:33 +0000 [info]: gem 'fluent-plugin-cloudwatch-logs' version '0.3.3'
2018-04-06 06:49:33 +0000 [info]: gem 'fluent-plugin-kubernetes_metadata_filter' version '0.32.0'
2018-04-06 06:49:33 +0000 [info]: gem 'fluent-plugin-prometheus' version '0.3.0'
2018-04-06 06:49:33 +0000 [info]: gem 'fluent-plugin-record-reformer' version '0.9.0'
2018-04-06 06:49:33 +0000 [info]: gem 'fluent-plugin-rewrite-tag-filter' version '1.5.6'
2018-04-06 06:49:33 +0000 [info]: gem 'fluent-plugin-secure-forward' version '0.4.5'
2018-04-06 06:49:33 +0000 [info]: gem 'fluentd' version '0.12.39'
2018-04-06 06:49:33 +0000 [info]: adding match pattern="fluent.**" type="null"
2018-04-06 06:49:33 +0000 [info]: adding filter pattern="kubernetes.**" type="kubernetes_metadata"
2018-04-06 06:49:33 +0000 [info]: adding filter pattern="kubernetes.**" type="record_transformer"
2018-04-06 06:49:33 +0000 [info]: adding match pattern="kubernetes.**" type="rewrite_tag_filter"
2018-04-06 06:49:33 +0000 [info]: adding rewrite_tag_filter rule: rewriterule1 ["kubernetes_namespace_container_name", /^(.+)$/, "", "kube.$1"]
2018-04-06 06:49:33 +0000 [info]: adding filter pattern="kube.**" type="record_transformer"
2018-04-06 06:49:33 +0000 [info]: adding filter pattern="kube.kube-system.**" type="parser"
2018-04-06 06:49:33 +0000 [info]: adding match pattern="**" type="cloudwatch_logs"
2018-04-06 06:49:33 +0000 [info]: adding source type="http"
2018-04-06 06:49:33 +0000 [info]: adding source type="monitor_agent"
2018-04-06 06:49:33 +0000 [info]: adding source type="prometheus"
2018-04-06 06:49:33 +0000 [info]: adding source type="prometheus_monitor"
2018-04-06 06:49:33 +0000 [info]: adding source type="prometheus_output_monitor"
2018-04-06 06:49:33 +0000 [info]: adding source type="prometheus_tail_monitor"
2018-04-06 06:49:33 +0000 [info]: adding source type="tail"
2018-04-06 06:49:33 +0000 [info]: adding source type="tail"
2018-04-06 06:49:33 +0000 [info]: using configuration file: <ROOT>
  <match fluent.**>
    type null
  </match>
  <source>
    @type http
    port 9880
    bind 0.0.0.0
  </source>
  <source>
    @type monitor_agent
    bind 0.0.0.0
    port 24220
    tag fluentd.monitor.metrics
  </source>
  <source>
    @type prometheus
    bind 0.0.0.0
    port 24231
    metrics_path /metrics
  </source>
  <source>
    @type prometheus_monitor
    interval 5
  </source>
  <source>
    @type prometheus_output_monitor
    interval 5
  </source>
  <source>
    @type prometheus_tail_monitor
    interval 5
  </source>
  <source>
    type tail
    path /var/log/containers/*.log
    pos_file /var/log/fluentd-containers.log.pos
    time_format %Y-%m-%dT%H:%M:%S.%NZ
    tag kubernetes.*
    format json
    read_from_head true
  </source>
  <source>
    type tail
    format multiline
    multiline_flush_interval 5s
    format_firstline /^\S+\s+AUDIT:/
    format1 /^(?<time>\S+) AUDIT:(?: (?:id="(?<id>(?:[^"\\]|\\.)*)"|ip="(?<ip>(?:[^"\\]|\\.)*)"|method="(?<method>(?:[^"\\]|\\.)*)"|user="(?<user>(?:[^"\\]|\\.)*)"|groups="(?<groups>(?:[^"\\]|\\.)*)"|as="(?<as>(?:[^"\\]|\\.)*)"|asgroups="(?<asgroups>(?:[^"\\]|\\.)*)"|namespace="(?<namespace>(?:[^"\\]|\\.)*)"|uri="(?<uri>(?:[^"\\]|\\.)*)"|response="(?<response>(?:[^"\\]|\\.)*)"|\w+="(?:[^"\\]|\\.)*"))*/
    time_format %FT%T.%L%Z
    path /var/log/kubernetes/kube-apiserver-audit.log
    pos_file /var/log/kube-apiserver-audit.log.pos
    tag kube-apiserver-audit
  </source>
  <filter kubernetes.**>
    type kubernetes_metadata
    merge_json_log true
    preserve_json_log true
  </filter>
  <filter kubernetes.**>
    @type record_transformer
    enable_ruby true
    <record>
      kubernetes_namespace_container_name ${record["kubernetes"]["namespace_name"]}.${record["kubernetes"]["container_name"]}
    </record>
  </filter>
  <match kubernetes.**>
    @type rewrite_tag_filter
    rewriterule1 kubernetes_namespace_container_name  ^(.+)$ kube.$1
  </match>
  <filter kube.**>
    @type record_transformer
    remove_keys kubernetes_namespace_container_name
  </filter>
  <filter kube.kube-system.**>
    type parser
    format kubernetes
    reserve_data true
    key_name log
    suppress_parse_error_log true
    format_firstline /^\w\d{4}/
    format1 /^(?<severity>\w)(?<time>\d{4} [^\s]*)\s+(?<pid>\d+)\s+(?<source>[^ \]]+)\] (?<message>.*)/
    time_format %m%d %H:%M:%S.%N
  </filter>
  <match **>
    type cloudwatch_logs
    log_group_name kubernetes-logs
    log_stream_name fluentd-cloudwatch
    auto_create_stream true
    buffer_chunk_limit 2M
    buffer_queue_limit 32
    flush_interval 10s
    max_retry_wait 30
    disable_retry_limit 
    num_threads 8
  </match>
</ROOT>
2018-04-06 06:49:33 +0000 [error]: unexpected error error_class=NameError error=#<NameError: uninitialized constant Aws::CloudWatchLogs>
  2018-04-06 06:49:33 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluent-plugin-cloudwatch-logs-0.3.3/lib/fluent/plugin/out_cloudwatch_logs.rb:67:in `start'
  2018-04-06 06:49:33 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.39/lib/fluent/agent.rb:71:in `block in start'
  2018-04-06 06:49:33 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.39/lib/fluent/agent.rb:70:in `each'
  2018-04-06 06:49:33 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.39/lib/fluent/agent.rb:70:in `start'
  2018-04-06 06:49:33 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.39/lib/fluent/root_agent.rb:108:in `start'
  2018-04-06 06:49:33 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.39/lib/fluent/engine.rb:237:in `start'
  2018-04-06 06:49:33 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.39/lib/fluent/engine.rb:187:in `run'
  2018-04-06 06:49:33 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.39/lib/fluent/supervisor.rb:570:in `run_engine'
  2018-04-06 06:49:33 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.39/lib/fluent/supervisor.rb:162:in `block in start'
  2018-04-06 06:49:33 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.39/lib/fluent/supervisor.rb:366:in `main_process'
  2018-04-06 06:49:33 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.39/lib/fluent/supervisor.rb:339:in `block in supervise'
  2018-04-06 06:49:33 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.39/lib/fluent/supervisor.rb:338:in `fork'
  2018-04-06 06:49:33 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.39/lib/fluent/supervisor.rb:338:in `supervise'
  2018-04-06 06:49:33 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.39/lib/fluent/supervisor.rb:156:in `start'
  2018-04-06 06:49:33 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.39/lib/fluent/command/fluentd.rb:173:in `<top (required)>'
  2018-04-06 06:49:33 +0000 [error]: /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2018-04-06 06:49:33 +0000 [error]: /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2018-04-06 06:49:33 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.12.39/bin/fluentd:5:in `<top (required)>'
  2018-04-06 06:49:33 +0000 [error]: /usr/bin/fluentd:22:in `load'
  2018-04-06 06:49:33 +0000 [error]: /usr/bin/fluentd:22:in `<main>'
2018-04-06 06:49:33 +0000 [info]: shutting down fluentd
2018-04-06 06:49:33 +0000 [info]: shutting down output type="null" plugin_id="object:2aae6c8ebbac"
2018-04-06 06:49:33 +0000 [info]: shutting down output type="rewrite_tag_filter" plugin_id="object:2aae6ce15c90"
2018-04-06 06:49:33 +0000 [info]: process finished code=0
2018-04-06 06:49:33 +0000 [warn]: process died within 1 second. exit

**Comment by riywo** [comment] 2018-04-10 02:44
Same error.

```
2018-04-10 02:25:28 +0000 [error]: unexpected error error_class=NameError error=#<NameError: uninitialized constant Aws::CloudWatchLogs>
```

**Comment by riywo** [comment] 2018-04-10 02:58
It seems that the fluentd image should use fluent-plugin-cloudwatch-logs v4.4 or later to support AWS SDK for Ruby v3. ref. https://github.com/ryotarai/fluent-plugin-cloudwatch-logs/pull/91

**Comment by ShadySQL** [comment] 2018-04-10 12:41
Same error. Service Mesh walkthrough also is a mess. Nothing works.

**Comment by christopherhein** [comment] 2018-04-17 23:59
Apologizes @ShadySQL & @arunkumarmurugesan  were you able to test this with the image referenced in @riywo comment?

Also @ShadySQL if you wouldn't mind the best way to help make this better would be an issue regarding what you are running into in the module, would you mind opening an issue with the output of errors you are seeing… thanks!

**Comment by arun-gupta** [comment] 2018-04-23 21:39
Duplicate of #287

**Closed by arun-gupta** 2018-04-23 21:39 UTC
