### ISSUE TITLE
Broken link in Configure the AWS CLI Section of Kubernetes - Setup Cloud9 Development Environment page

### ISSUE THREAD

**Issue by C24IO** [aws-samples/aws-workshop-for-kubernetes#453] opened 2018-05-10 01:48 UTC
In this section - 

https://github.com/aws-samples/aws-workshop-for-kubernetes/tree/master/01-path-basics/101-start-here#configure-the-aws-cli

This line - Make sure you are logged in as a user with these permissions.

This is the broken link - https://github.com/aws-samples/aws-workshop-for-kubernetes/blob/master/01-path-basics/101-start-here/aws-permissions.adoc

**Comment by geremyCohen** [comment] 2018-06-15 17:06
@buzzsurfr the file doesn't appear to exist, and doesn't appear in the git history.  Can you give me a hint to what "these permissions" and/or aws-permissions.adoc is supposed to contain, and I can take it from there?

**Comment by geremyCohen** [comment] 2018-06-21 20:42
Will create docs that list the permissions needed to run the workshop.

**Comment by geremyCohen** [comment] 2018-06-27 18:21
Dupe of https://github.com/aws-samples/aws-workshop-for-kubernetes/issues/340

**Comment by geremyCohen** [comment] 2018-07-06 00:34
https://github.com/aws-samples/aws-workshop-for-kubernetes/pull/516

**Closed** 2018-07-06 17:04 UTC
Labels: bug, duplicate, help wanted
